object Versions {
    const val ANDROID_GRADLE_PLUGIN_VERSION = "7.2.2"
    const val KOTLIN_VERSION = "1.7.20"
    const val APP_COMPAT_VERSION = "1.5.1"
    const val MATERIAL_DESIGN_VERSION = "1.6.1"
    const val CONSTRAINT_LAYOUT_VERSION = "2.1.4"
    const val NAVIGATION_VERSION = "2.5.2"
    const val NAV_SAFE_ARGS_VERSION = "2.5.2"
    const val CORE_KTX_VERSION = "1.9.0"
    const val KOIN_VERSION = "3.2.2"
    const val ROOM_VERSION = "2.4.3"
    const val GLIDE_VERSION = "4.12.0"
    const val RETROFIT_VERSION = "2.9.0"
    const val HTTP_INTERCEPTOR_VERSION = "4.9.1"
    const val GSON_VERSION = "2.9.1"
    const val COROUTINES_VERSION = "1.4.1"
    const val LIFECYCLE_VERSION = "2.4.0"
    const val JUNIT4_VERSION = "4.13.2"
    const val MOCKK_VERSION = "1.12.3"
    const val ESPRESSO_VERSION = "3.4.0"
    const val JUNIT_EXT_VERSION = "1.1.3"
}